# Generated by Django 6.0.2 on 2026-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="default_from_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_host",
            field=models.CharField(
                blank=True, default="smtp.gmail.com", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_host_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_host_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_port",
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_use_tls",
            field=models.BooleanField(default=True),
        ),
    ]
