# Generated by Django 6.0.2 on 2026-05-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("seller", "Seller"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
