# Generated by Django 6.0.2 on 2026-05-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_coupon_max_discount_remove_coupon_valid_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("online", "Online Payment"), ("cod", "Cash on Delivery")],
                default="online",
                max_length=10,
            ),
        ),
    ]
