# Generated by Django 6.0.2 on 2026-05-16 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_coupon_tenant_order_tenant_alter_coupon_code_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.tenant",
            ),
        ),
    ]
