# Generated by Django 6.0.2 on 2026-05-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_category_tenant_product_tenant_alter_category_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
