# Generated by Django 6.0.2 on 2026-05-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="categories/"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(max_length=500, upload_to="products/"),
        ),
    ]
