# Generated by Django 6.0.5 on 2026-05-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_category_image_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.CharField(
                blank=True, help_text="Comma-separated sizes", max_length=255, null=True
            ),
        ),
    ]
